In [1]:
import pandas as pd
import numpy as np

In [3]:
students = pd.read_csv("student_scores.csv")
subjects = pd.read_csv("subjects.csv")

students

   student_id              name  math  physics  cs
0           1       Иванов Иван    78       82  91
1           2       Петров Петр    55       60  58
2           3     Сидорова Анна    92       88  95
3           4  Кузнецов Алексей    40       50  45
4           5    Смирнова Мария    67       73  70

In [4]:
def calculate_results(students_df, subjects_df):
    # TODO:
    # 1. создать словарь весов предметов
    # 2. посчитать взвешенную сумму
    # 3. определить passed
    
    ### BEGIN SOLUTION
    
    weights = dict(zip(subjects_df["subject"], subjects_df["weight"]))
    
    students_df["final_score"] = (
        students_df["math"] * weights["math"] +
        students_df["physics"] * weights["physics"] +
        students_df["cs"] * weights["cs"]
    )
    
    students_df["passed"] = (
        (students_df["math"] >= 55) &
        (students_df["physics"] >= 55) &
        (students_df["cs"] >= 55)
    )
    
    return students_df
    
    ### END SOLUTION

In [5]:
results = calculate_results(students, subjects)
results

   student_id              name  math  physics  cs  final_score  passed
0           1       Иванов Иван    78       82  91         84.4    True
1           2       Петров Петр    55       60  58         57.7    True
2           3     Сидорова Анна    92       88  95         92.0    True
3           4  Кузнецов Алексей    40       50  45         45.0   False
4           5    Смирнова Мария    67       73  70         70.0    True

In [7]:
# Tests 10 points.


test_students = pd.DataFrame({
    "student_id": [1],
    "name": ["Test"],
    "math": [80],
    "physics": [70],
    "cs": [90]
})

test_subjects = pd.DataFrame({
    "subject": ["math", "physics", "cs"],
    "weight": [0.3, 0.3, 0.4]
})

result = calculate_results(test_students.copy(), test_subjects)

# проверка структуры
assert "final_score" in result.columns
assert "passed" in result.columns

# проверка вычисления итогового балла
expected_score = 80*0.3 + 70*0.3 + 90*0.4
assert round(result.loc[0, "final_score"], 5) == round(expected_score, 5)

# проверка passed
assert result.loc[0, "passed"] == True


### BEGIN HIDDEN TESTS

students_hidden = pd.DataFrame({
    "student_id": [2, 3],
    "name": ["A", "B"],
    "math": [50, 90],
    "physics": [60, 90],
    "cs": [70, 90]
})

subjects_hidden = pd.DataFrame({
    "subject": ["math", "physics", "cs"],
    "weight": [0.3, 0.3, 0.4]
})

hidden_result = calculate_results(students_hidden.copy(), subjects_hidden)

# студент не проходит если хотя бы один предмет < 55
assert hidden_result.loc[0, "passed"] == False

# студент проходит если все >= 55
assert hidden_result.loc[1, "passed"] == True

# проверка weighted score
expected_hidden_score = 90*0.3 + 90*0.3 + 90*0.4
assert round(hidden_result.loc[1, "final_score"], 5) == round(expected_hidden_score, 5)

# проверка работы с несколькими строками
assert len(hidden_result) == 2

### END HIDDEN TESTS